engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: false
ratings:
  paths:
  - lib/**.js
exclude_paths:
  - node_modules/**
  - test/**
